CREATE OR REPLACE PROCEDURE CALC_THRESHOLD
AS
    CONS_RATE NUMBER(10,2);
    THRESHOLD_VAL_CALC INTEGER;
    REF_SUP_ID NUMBER(10);
BEGIN
    FOR IND IN (SELECT * FROM INVENTORY)
    LOOP
        SELECT SUPPLIER_ID
        INTO REF_SUP_ID
        FROM PSA_T A, PSA_LINE_T B
        WHERE A.PSA_ID=B.PSA_ID
        AND ITEM_NO=IND.ITEM_NO
        AND A.END_DATE IS NULL
        AND ROWNUM=1;
        
        SELECT LEADTIME
        INTO REF_LEADTIME
        FROM LEADTIME_T
        WHERE ITEM_NO=IND.ITEM_NO
        AND SUP_ID=REF_SUP_ID;
        
        SELECT FCAST_VAL
        INTO REF_FCAST_VAL
        FROM ITEM_FCAST_T
        WHERE ITEM_NO=IND.ITEM_NO;
        
        CONS_RATE:=REF_FCAST_VAL/30;
        THRESHOLD_VAL_CALC:=IND.SAFETY_STOCK+(CONS_RATE*REF_LEADTIME);
        
        UPDATE INVENTORY
        SET THRESHOLD_VAL=THRESHOLD_VAL_CALC
        WHERE ITEM_NO=IND.ITEM_NO;
    END LOOP;
END;
/
COMMIT;