CREATE OR REPLACE PROCEDURE FF_REFILL(REQ_ID_IN IN REFILL_REQUEST.REQ_ID%TYPE, ITEM_NO_IN IN REFILL_REQUEST_LINE.ITEM_NO%TYPE, ITEM_QTY_IN IN REFILL_REQUEST_LINE.ITEM_QTY%TYPE)
AS
    INV_ITEM_QTY INTEGER;
    I INTEGER;
    ITEM_QTY_INV_LINE INTEGER;
    NEW_QTY INTEGER;
BEGIN
    SELECT QTY
    INTO INV_ITEM_QTY
    FROM INVENTORY
    WHERE ITEM_NO=ITEM_NO_IN;
    
    I:=ITEM_QTY_IN;

    IF(INV_ITEM_QTY>ITEM_QTY_IN) THEN
        WHILE(I<>0)
        LOOP
            SELECT UNITS
            INTO ITEM_QTY_INV_LINE
            FROM INVENTORY_LINE
            WHERE ITEM_NO=ITEM_NO_IN
            AND ROWNUM=1
            AND EXPIRY_DATE>SYSDATE+7;
        
            DELETE FROM INVENTORY_LINE
            WHERE ITEM_NO=ITEM_NO_IN
            AND ROWNUM=1
            AND EXPIRY_DATE>SYSDATE+7;
            
            I:=I-ITEM_QTY_INV_LINE;
        END LOOP;
        
        UPDATE REFILL_REQUEST_LINE
        SET DEL_DATE=SYSDATE
        WHERE REQ_ID=REQ_ID_IN
        AND ITEM_NO=ITEM_NO_IN
        AND ITEM_QTY=ITEM_QTY_IN;
        
        SELECT SUM(UNITS)
        INTO NEW_QTY
        FROM INVENTORY_LINE
        WHERE ITEM_NO=ITEM_NO_IN;
        
        UPDATE INVENTORY
        SET QTY=NEW_QTY
        WHERE ITEM_NO=ITEM_NO_IN;
        
        COMMIT;
    END IF;
END;