CREATE OR REPLACE TRIGGER INV_THRESHOLD_TRIG
AFTER UPDATE OR INSERT
ON INVENTORY
FOR EACH ROW

BEGIN
    IF(:new.QTY<:new.THRESHOLD_VAL) THEN
        AUTO_ORDER(:new.ITEM_NO);
    END IF;
END;