CREATE OR REPLACE PROCEDURE ITEM_FCAST
AS
BEGIN
  FOR IND IN (SELECT DISTINCT(ITEM_NO) FROM PSA_T A, PSA_LINE_T B 
  WHERE A.PSA_ID=B.PSA_ID AND END_DATE IS NULL)
  LOOP
    INSERT INTO ITEM_FCAST_T
    VALUES(IND.ITEM_NO, SYSDATE, NULL, SYSDATE);
  
    UPDATE ITEM_FCAST_T
    SET FCAST_VAL=SET_FVAL(IND.ITEM_NO);
  END LOOP;
END;