CREATE OR REPLACE FUNCTION SET_FVAL(ITEM_NO_IN IN PSA_LINE_T.ITEM_NO%TYPE)
RETURN INTEGER AS
    FCAST_VAL_OUT integer;

    CMON_CYR_Q INTEGER;
    L1MON_CYR_Q INTEGER;
    L2MON_CYR_Q INTEGER;
    CMON_LYR_Q INTEGER;
    L1MON_LYR_Q INTEGER;
    L2MON_LYR_Q INTEGER;
BEGIN
    SELECT SUM(QTY)
    INTO CMON_CYR_Q
    FROM CUSTOMER_ORDER A, CUSTOMER_ORDER_LINE B
    WHERE A.ORDER_ID=B.ORDER_ID
    AND EXTRACT(MONTH FROM TRANS_DATE)=EXTRACT(MONTH FROM SYSDATE)
    AND EXTRACT(YEAR FROM TRANS_DATE)=EXTRACT(YEAR FROM SYSDATE);

    SELECT SUM(QTY)
    INTO L1MON_CYR_Q
    FROM CUSTOMER_ORDER A, CUSTOMER_ORDER_LINE B
    WHERE A.ORDER_ID=B.ORDER_ID 
    AND EXTRACT(MONTH FROM TRANS_DATE)=EXTRACT(MONTH FROM SYSDATE)-1
    AND EXTRACT(YEAR FROM TRANS_DATE)=EXTRACT(YEAR FROM SYSDATE);
    
    SELECT SUM(QTY)
    INTO L2MON_CYR_Q
    FROM CUSTOMER_ORDER A, CUSTOMER_ORDER_LINE B
    WHERE A.ORDER_ID=B.ORDER_ID 
    AND EXTRACT(MONTH FROM TRANS_DATE)=EXTRACT(MONTH FROM SYSDATE)-2
    AND EXTRACT(YEAR FROM TRANS_DATE)=EXTRACT(YEAR FROM SYSDATE);
    
    SELECT SUM(QTY)
    INTO CMON_LYR_Q
    FROM CUSTOMER_ORDER A, CUSTOMER_ORDER_LINE B
    WHERE A.ORDER_ID=B.ORDER_ID 
    AND EXTRACT(MONTH FROM TRANS_DATE)=EXTRACT(MONTH FROM SYSDATE)
    AND EXTRACT(YEAR FROM TRANS_DATE)=EXTRACT(YEAR FROM SYSDATE)-1;
    
    SELECT SUM(QTY)
    INTO L1MON_LYR_Q
    FROM CUSTOMER_ORDER A, CUSTOMER_ORDER_LINE B
    WHERE A.ORDER_ID=B.ORDER_ID
    AND EXTRACT(MONTH FROM TRANS_DATE)=EXTRACT(MONTH FROM SYSDATE)-1
    AND EXTRACT(YEAR FROM TRANS_DATE)=EXTRACT(YEAR FROM SYSDATE)-1;
    
    SELECT SUM(QTY)
    INTO L2MON_LYR_Q
    FROM CUSTOMER_ORDER A, CUSTOMER_ORDER_LINE B
    WHERE A.ORDER_ID=B.ORDER_ID
    AND EXTRACT(MONTH FROM TRANS_DATE)=EXTRACT(MONTH FROM SYSDATE)-2
    AND EXTRACT(YEAR FROM TRANS_DATE)=EXTRACT(YEAR FROM SYSDATE)-1;

    FCAST_VAL_OUT:=(CMON_CYR_Q+L1MON_CYR_Q+L2MON_CYR_Q+CMON_LYR_Q+L1MON_LYR_Q+L2MON_LYR_Q)/6;
    
    RETURN FCAST_VAL_OUT;
END;